### ISSUE TITLE
Create an ogranization template

### ISSUE THREAD

**Issue by AlexZhukovich** [artificialrevelations/artificialrevelations.github.io#1]
A website should have the sections:
- header (image + welcome text + name of organization)
- libraries (list of projects)
- workshops (list of workshops)
- presentation (list of presentations)
- contacts (card for each person -> { name, email, photo, twitter, blog, github, additional links (youtube channel) })
- footer (copyright + site map)

**Comment by ajoz** [comment]
@AlexZhukovich Maybe this should be split into several tasks?

**Comment by AlexZhukovich** [comment]
@ajoz maybe it's a great idea. Perhaps we can start from header, libraries and footer for the first issue. What do you think?

**Comment by ajoz** [comment]
I agree

**Comment by AlexZhukovich** [comment]
I created the following issues:
* Create base version of organization website (#2)
* Add a workshop section to organization website (#3)
* Add a presentation section to the organization website (#4)
* Add a contact section to the organization website (#5)
